# Generated by Django 5.1.6 on 2025-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, default="default.jpg", upload_to="images/"
                    ),
                ),
            ],
        ),
    ]
